spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_system?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: order_system
    password: order_system
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: localhost
      port: 27017
#      authentication-database: admin
      username: commerce
      password: commerce
      database: commerce
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: group_1
logging:
  level:
    '[org.apache.kafka.clients.consumer.internals.ConsumerCoordinator]': warn
    '[org.apache.kafka.clients.consumer.ConsumerConfig]': warn
