spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:order_system
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-server: localhost:9092