spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:order_system
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-server: localhost:9092
    consumer:
      group-id: group_1

security:
  secret-key: ABCD

cors:
  domain: http://localhost:5173